export const fecthData = {
  primaryObj: '',
  subObjs: [],
  relatedObjects: [
    {
      objSel: "",
      objs: "",
      relatedObjects: [],
    },
  ],
  objs: [
    {
      groupName: "",
      objectApiName: "User",
      objectName: "User",
      objectReferenceField: {
        fieldAccess: "F",
        fieldApiName: "OwnerId",
        fieldName: "Owner",
        fieldRelationshipName: "Owner",
        fieldType: "",
      },
    },
    {
      groupName: "",
      objectApiName: "User1",
      objectName: "User1",
      objectReferenceField: {
        fieldAccess: "F",
        fieldApiName: "OwnerId",
        fieldName: "Owner",
        fieldRelationshipName: "Owner",
        fieldType: "",
      },
    },
    {
      groupName: "",
      objectApiName: "User2",
      objectName: "User2",
      objectReferenceField: {
        fieldAccess: "F",
        fieldApiName: "OwnerId",
        fieldName: "Owner",
        fieldRelationshipName: "Owner",
        fieldType: "",
      },
    },
    {
      groupName: "",
      objectApiName: "User3",
      objectName: "User3",
      objectReferenceField: {
        fieldAccess: "F",
        fieldApiName: "OwnerId",
        fieldName: "Owner",
        fieldRelationshipName: "Owner",
        fieldType: "",
      },
    },
    {
      groupName: "",
      objectApiName: "User3",
      objectName: "User4",
      objectReferenceField: {
        fieldAccess: "F",
        fieldApiName: "OwnerId",
        fieldName: "Owner",
        fieldRelationshipName: "Owner",
        fieldType: "",
      },
    },
    {
      groupName: "",
      objectApiName: "User3",
      objectName: "User5",
      objectReferenceField: {
        fieldAccess: "F",
        fieldApiName: "OwnerId",
        fieldName: "Owner",
        fieldRelationshipName: "Owner",
        fieldType: "",
      },
    },
    {
      groupName: "",
      objectApiName: "User3",
      objectName: "User6",
      objectReferenceField: {
        fieldAccess: "F",
        fieldApiName: "OwnerId",
        fieldName: "Owner",
        fieldRelationshipName: "Owner",
        fieldType: "",
      },
    },
    {
      groupName: "",
      objectApiName: "User3",
      objectName: "User7",
      objectReferenceField: {
        fieldAccess: "F",
        fieldApiName: "OwnerId",
        fieldName: "Owner",
        fieldRelationshipName: "Owner",
        fieldType: "",
      },
    },
    {
      groupName: "",
      objectApiName: "User3",
      objectName: "User8",
      objectReferenceField: {
        fieldAccess: "F",
        fieldApiName: "OwnerId",
        fieldName: "Owner",
        fieldRelationshipName: "Owner",
        fieldType: "",
      },
    },
    {
      groupName: "",
      objectApiName: "User3",
      objectName: "User10",
      objectReferenceField: {
        fieldAccess: "F",
        fieldApiName: "OwnerId",
        fieldName: "Owner",
        fieldRelationshipName: "Owner",
        fieldType: "",
      },
    },
    {
      groupName: "",
      objectApiName: "User3",
      objectName: "User9",
      objectReferenceField: {
        fieldAccess: "F",
        fieldApiName: "OwnerId",
        fieldName: "Owner",
        fieldRelationshipName: "Owner",
        fieldType: "",
      },
    },
  ],

};

export const subObjsData = [
  {
    groupName: "lookup",
    objectApiName: "User",
    objectName: "Contact",
    objectReferenceField: {
      fieldAccess: "F",
      fieldApiName: "OwnerId",
      fieldName: "Owner",
      fieldRelationshipName: "Owner",
      fieldType: "Lookup",
    },
  },
  {
    groupName: "lookup",
    objectApiName: "User1",
    objectName: "User1",
    objectReferenceField: {
      fieldAccess: "F",
      fieldApiName: "OwnerId",
      fieldName: "Owner",
      fieldRelationshipName: "Owner",
      fieldType: "Lookup",
    },
  },
  {
    groupName: "lookup",
    objectApiName: "User2",
    objectName: "User2",
    objectReferenceField: {
      fieldAccess: "F",
      fieldApiName: "OwnerId",
      fieldName: "Owner",
      fieldRelationshipName: "Owner",
      fieldType: "Lookup",
    },
  },
  {
    groupName: "lookup",
    objectApiName: "User3",
    objectName: "User3",
    objectReferenceField: {
      fieldAccess: "F",
      fieldApiName: "OwnerId",
      fieldName: "Owner",
      fieldRelationshipName: "Owner",
      fieldType: "Lookup",
    },
  },
  {
    groupName: "lookup",
    objectApiName: "User3",
    objectName: "User4",
    objectReferenceField: {
      fieldAccess: "F",
      fieldApiName: "OwnerId",
      fieldName: "Owner",
      fieldRelationshipName: "Owner",
      fieldType: "Lookup",
    },
  },
  {
    groupName: "lookup",
    objectApiName: "User3",
    objectName: "User5",
    objectReferenceField: {
      fieldAccess: "F",
      fieldApiName: "OwnerId",
      fieldName: "Owner",
      fieldRelationshipName: "Owner",
      fieldType: "Lookup",
    },
  },
  {
    groupName: "lookup",
    objectApiName: "User3",
    objectName: "User6",
    objectReferenceField: {
      fieldAccess: "F",
      fieldApiName: "OwnerId",
      fieldName: "Owner",
      fieldRelationshipName: "Owner",
      fieldType: "Account",
    },
  },
  {
    groupName: "Accounts",
    objectApiName: "User3",
    objectName: "User7",
    objectReferenceField: {
      fieldAccess: "F",
      fieldApiName: "OwnerId",
      fieldName: "Owner",
      fieldRelationshipName: "Owner",
      fieldType: "Account",
    },
  },
  {
    groupName: "",
    objectApiName: "User3",
    objectName: "User8",
    objectReferenceField: {
      fieldAccess: "F",
      fieldApiName: "OwnerId",
      fieldName: "Owner",
      fieldRelationshipName: "Owner",
      fieldType: "Account",
    },
  },
  {
    groupName: "",
    objectApiName: "User3",
    objectName: "User10",
    objectReferenceField: {
      fieldAccess: "F",
      fieldApiName: "OwnerId",
      fieldName: "Owner",
      fieldRelationshipName: "Owner",
      fieldType: "Account",
    },
  },
  {
    groupName: "",
    objectApiName: "User3",
    objectName: "User9",
    objectReferenceField: {
      fieldAccess: "F",
      fieldApiName: "OwnerId",
      fieldName: "Owner",
      fieldRelationshipName: "Owner",
      fieldType: "Account",
    },
  },
];
